name: Terraform Validate

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  terraform-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Validate
        run: terraform validate
