name: Terraform Validate

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  terraform-validate:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      AWS_BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
      AWS_REGION: ${{ secrets.REGION }}
      KEY_NAME: ${{ secrets.KEY_NAME }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.6.5

      - name: Terraform Init
        run: terraform init -backend-config="bucket=${BUCKET_NAME}" -backend-config="region=${REGION}" -backend-config="key=${KEY_NAME}"


      - name: Terraform Validate
        run: terraform validate
